config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.shortcuts import render
from . import views
from django.urls import path

app_name = "website"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('intro', views.intro_page_view, name='intro'),
    path('multi', views.multi_page_view, name='multi')
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
import datetime

# Create your views here.
def home_page_view(request):
    lista = ["HTML", "CSS", "Python", "Django"]
    context = {
        'agora': datetime.datetime.now(),
        'lista': lista,
    }
    return render(request, 'website/home.html', context)


def intro_page_view(request):
    return render(request, 'website/intro.html')

def multi_page_view(request):
    return render(request, 'website/multi.html')

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Django Website</title>
</head>
<body>
    <header class="jumbotron text-center">
        <h1>Website Django</h1>
        <p>O meu primeiro Django Website</p>
        <nav>
            <a href="{% url 'website:home' %}" class="btn btn-info">Home</a>
            <a href="{% url 'website:intro' %}"class="btn btn-info">Intro</a>
            <a href="{% url 'website:multi' %}" class="btn btn-info">Multi</a>
        </nav>
    </header>
    <article class="container">
        <main class="col-sm-6">
	            {% block main %}
                {% endblock main %}
</main>
        <aside class="col-sm-6">
            {% load static %}
            <img src="{% static 'website/images/e.jpg' %}">
        </aside>
    </article>
    <footer>E O SPORTING É CAMPEÃO</footer>
</body>
</html>

website/templates/website/home.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>DUBAI QUER O SPORTING BICAMPEÃO</h3>
    <p>Este é o website sobre Django e uma perspetiva sobre a inacreditável conquista do SCP</p>
{% endblock %}

website/templates/website/intro.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Django</h3>
    <p>O POTE é o melhor marcador !! Toma Seferopipocas haha</p>
    {% load static %}
    <img src="{% static 'website/images/pote.jpg' %}">
{% endblock %}

website/templates/website/multi.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>DUBAI QUER O SPORTING BICAMPEÃO</h3>
    <p> É evidente que esta foi a melhor época do Campeão Sporting CP  </p>
{% endblock %}